### ISSUE TITLE
Not Thread-safe!? Benign Data Race?

### ISSUE THREAD

**Issue by couchdeveloper** [robertmryan/Operation-Test-Swift#2]
I've have some concerns whether this approach is thread-safe and whether possible phenomena due to data races may have a harmful effect. I would like to analyse the problem.

The backing variable `_executing` and also `_finished` _may_ be accessed concurrently from different threads, without using synchronisation. This is a classic data race.

Now, the question arises what anomalies this may cause - if any.

First, we could improve the design making the setters for `finished` and `executing` private. But anyway, a client can only ever _read_ the variables. The operation instance will be responsible for setting the variables. KVO is a client here, for example.

When `start` will be called, property `executing` will be set to `true`. If an observer has been registered for the property, it causes KVO to read the backing value (before and after setting it) and pass a copy to the observers. This executes all on the same thread where `start` has been executed.

If, `completeOperation()` executes (on an arbitrary thread) it sets the backing variables `_executing` and `_finished`. This causes KVO to read the old variables and - after modifying - the new variables _on the same thread_  and sending it to an observer.  So, we might have an issue here, when KVO reads the old backing store variable, which has been set on a different thread when starting the operation. We cannot always assume, that when executing on the current thread, this variable is _current_ (see weakly ordered memory model, e.g. ARM). After the variables have been set, it will be safe to read them again on the same thread.

So, from the perspective of an observer, we _may_ assume, that receiving the old values _may_ be bogus - and that receiving new values are correct. KVO notifies this to its observers on whatever thread is executing `completeOperation()`. If a client would access the respective property (in order to obtain the current value) when handling the event on the same thread it can be assumed to be safe as well.

We also have a scenario where reading the variables may happen at any time from a client from zero to many times on any thread. And concurrently, the variables will be modified on an arbitrary other thread by the operation. From the perspective of the client, this again _may_ not be safe - especially in a weakly ordered memory model. It's a data race, and the client may possibly read "stale" or clobbered values - and not actual the current ones.

We may say, this hardly affects clients, reading a `Bool` is atomic after all. And _eventually_ we may get the current value - if we happen to execute in the same thread where it has been set, or if a global fence has been executed elsewhere, that synchronises all threads, etc. 

But data races lead to undefined behaviour, and we do not know, how the Swift compiler applies optimisations, which may make the matter worse. But how much? For example, optimisations may make a copy of the property value storing it in a register when iterating in a loop (I don't think Swift will make this assumption, though).

This data race issue can be fixed, but it is quite cumbersome (due to KVO accessing the getter when the setter was invoked). Is it worth doing it?

**Comment by robertmryan** [comment]
I don't think it's an issue in this simple test in which I'm merely demonstrating that the use of `finished` and `executing` for the KVO keys is inappropriate, but I've updated this to make the accessors, at least, thread-safe in a manner similar to what Apple did in their sample code that accompanied WWDC 2015 video [Advanced NSOperations](https://developer.apple.com/videos/play/wwdc2015/226/).

**Comment by couchdeveloper** [comment]
Looks OK, now. ;)

**Comment by flexaddicted** [comment]
@couchdeveloper Your explanation is simply amazing. I understood your point but I'm struggling a little bit why the old value can be bogus while the new one is correct. But maybe now I cannot think to an useful example.

**Comment by couchdeveloper** [comment]
@flexaddicted Well, you are right: in the completely _unsynchronised_ approach, _any_ access to a variable with a data race is undefined. That is, even the _newValue_, which is sent to the client by KVO _can_ be bogus, if that _newValue_ will be obtained from the backing variable (e.g. `_executing` which is accessed concurrently by another thread).

Lets look at the variable `_executing` and emphasise on its accesses only:

Here, we have two threads: 

Thread A, is the thread where the `start` method is executed and where the variable `_executing` is set to `1`.

The underlying task signals its completion on Thread B, that is, on Thread B, the property `executing` will be set to `0`.  

**Unsynchronised access:**

```
time                    Thread A        Thread B
|   Operation start
| 
v                       _executing = 1

    Operation will finish
                                        var oldValue = _executing // in willChangeValueForKey
                                        _executing = 0
                                        var newValue = _executing // in didChangeValueForKey
```

In the completely unsynchronised approach, we _cannot make any guarantees about the actual order_ of these accesses _between theses two threads_. That is, even though  "in our perceived time" `_executing = 0` happens later than `_executing = 1`, it doesn't mean that the memory store of variable `_executing` will be accessed in the same order! What happens in the CPU and the memory is not synchronised with the time axis in the above picture!

So, what _might_ happen hypothetically in terms of "operations" on shared memory is this:

```
Operations      Thread A           Thread B
| 
v
                                   var oldValue = read _executing 
                write _executing, 1
                                   write _executing, 0
                                   var newValue = read _executing
```

(This is an extremely simplified view what actually happens on a hardware with many CPUs, caches, pipelines and possibly weakly ordered memory!)

We can now speculate a lot, and imagine scenarios considering different hardware where the variable `newValue` equals actually and reliable _zero_, since it has been set on the same thread immediately before being read, and the first write access happened a "significant duration" before the read access -- but this is futile: without synchronisation primitives, this approach has a data race and thus, the behaviour is undefined. In my previous description, I was tempted to be more lax (which I believe matches the real result in any scenario in this case), but strictly - it is undefined behaviour.

Please note, that the recent changes made by Rob fixed this issue! It looks more like this below now:

If we look again at what the operations looks like, when emphasising on the accesses and memory barriers, that guarantee an order of the operations made on different threads:

**Synchronised access:**

```
time                    Thread A        Thread B
|   Operation start
| 
v                       _executing = 1
                        MemoryBarrier 1

    Operation will finish
                                        MemoryBarrier 2  // this ensures, that all operations before
                                                                    // MemoryBarrier 1 have been executed.
                                        var oldValue = _executing // in willChangeValueForKey
                                        _executing = 0
                                        var newValue = _executing // in didChangeValueForKey
```

In terms of operations related to shared memory, we have this now:

```
Operations      Thread A           Thread B
| 
v
                write _executing, 0
                memory_barrier_release
                                   memory_barrier_acquire
                                   var oldValue = read _executing 
                                   write _executing, 1
                                   var newValue = read _executing
```

This pair of memory barriers now guarantee a "Happens Before"  and a "Is Synchronised With" relationship between the operations performed on thread A and the operations performed on thread B.

That is, what ever operation executed _before_ `memory_barrier_release` on thread A, has been "committed" to the shared memory store and is _visible_ to thread B _after_ executing `memory_barrier_acquire`.

Note: the setter of property `executing` is implemented as follows:

```
    override private(set) var executing: Bool {
        set {
            willChangeValueForKey("isExecuting")
           _executing = newValue
            didChangeValueForKey("isExecuting")
        }
    }

```

**Comment by flexaddicted** [comment]
@couchdeveloper Thanks for your brilliant answer! Let me go through and I will let you know! P.S. I think also you can take a look to my question [xctest-stall-on-main-thread-behaviour](http://stackoverflow.com/questions/37435339/asynchronous-nsoperation-and-xctest-stall-on-main-thread-behaviour). Thanks!!

**Comment by flexaddicted** [comment]
@couchdeveloper I read through your reply. One doubt I have is in this diagram. Should the red boxes be swapped? 

<img width="400" alt="image" src="https://cloud.githubusercontent.com/assets/1482350/15555041/c96ded12-22be-11e6-9d48-0c31c65c1315.png">

Based on the sequence of instructions of an `NSOperation`, the `start` method should execute always before the `main` method. So, the `_executing` flag will be always consistent. So, the overlapping due to interleaving (and hence race condition) should not be there. The problem can arise instead if someone registers as an KVO observer for that property. But also at this point the order execution of `start` and `main` methods will be sufficient to have a consistent value. Am I missing something?

**Comment by couchdeveloper** [comment]
> Should the red boxes be swapped?

Yes, you are right - in thread A, `start` sets `_executing` to `1` and in thread B, the operation finishes and sets `_executing` to `0`. Sorry, for the typo. Fixed.

> Based on the sequence of instructions of an NSOperation, the start method should execute always before the main method. So, the _executing flag will be always consistent. So, the overlapping due to interleaving (and hence race condition) should not be there. 

Well, this is exactly the issue: you cannot (generally) make assumptions about the order of operations performed on different threads. We do not known if the compiler thinks that reordering a few statements will still guarantee the semantics on thread A. So, for example - it might think that 1. starting the task, then 2. setting the flag is semantically the same as 1. setting the flag, 2. starting the task. But even if the compiler thinks, it cannot make this reordering, we are not on the safe side:
We do not know whether the _CPU_ is reordering the instruction whilst maintaining the original semantics of the statements within the thread. So, the CPU can reorder statements as well.
And even further, we do not know whether any write to a memory store on thread A, is _visible_ to another thread at the time when it reads the same memory store - even the write happened a _significant_ duration before (in relation to CPU speed). Think of the write being _asynchronous_ and _lazy_ (due to several caches).

So, yes - the approach without synchronisation has a data race.

**Comment by flexaddicted** [comment]
@couchdeveloper Sorry for the late reply! Yep! I understand your point. Thanks for the detailed explanation. Also the latest figure has values swapped. P.S. Do you suggest any good manual in order to grasp (in a more under the hood way) how things work in a multithreading environment?

**Comment by robertmryan** [comment]
IMHO, the general rule is simple: If it can be mutated from one thread while being accessed from another, you should synchronize your access to it. See [Synchronization](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/ThreadSafety/ThreadSafety.html#//apple_ref/doc/uid/10000057i-CH8-SW1) chapter from the _Threading Programming Guide._

Or see [Eliminating Lock-Based Code](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ThreadMigration/ThreadMigration.html#//apple_ref/doc/uid/TP40008091-CH105-SW3) in the _Concurrency Programming Guide_ for advice on how to use dispatch queues to replace lock-based code.

**Comment by robertmryan** [comment]
BTW, in addition to the serial GCD queue described in the _Concurrency Programming Guide,_ Apple also discusses a refinement, the reader-writer pattern in the latter part of WWDC 2012 video [Asynchronous Design Patterns with Blocks, GCD, and XPC](https://developer.apple.com/videos/wwdc/2012/?id=712).

**Comment by flexaddicted** [comment]
@robertmryan Thanks for the tips

**Comment by couchdeveloper** [comment]
@flexaddicted  Beyond searching the wiki for related terms (data race, race condition, benign data races, weakly ordered memory, sequential consistency, etc) here are my favourite blogs and articles:

Jeff Preshing's great blog:
- [This Is Why They Call It a Weakly-Ordered CPU](http://preshing.com/20121019/this-is-why-they-call-it-a-weakly-ordered-cpu/)
- [Acquire and Release Semantics](http://preshing.com/20120913/acquire-and-release-semantics/)
- [The Happens-Before Relation](http://preshing.com/20130702/the-happens-before-relation/)
- [The Synchronizes-With Relation](http://preshing.com/20130823/the-synchronizes-with-relation/)

Hans Boehm's paper: [How to miscompile programs with "benign" data races](https://www.usenix.org/legacy/events/hotpar11/tech/final_files/Boehm.pdf)

Bartosz Milewski's great [blog](https://bartoszmilewski.com), for example
- [Dealing with Benign Data Races the C++ Way](https://bartoszmilewski.com/2014/10/25/dealing-with-benign-data-races-the-c-way/)
  (and many more)

John Regehr's [blog](http://blog.regehr.org), for example
- [Race Condition vs. Data Race](http://blog.regehr.org/archives/490)
  (and many more)

Dmitry Vyokov's post:
- [Benign data races: what could possibly go wrong?](https://software.intel.com/en-us/blogs/2013/01/06/benign-data-races-what-could-possibly-go-wrong)

Herb Sutter on "Lockless Programming", about atomicity, operation reordering and memory barriers:
[Lockless Programming ](https://msdn.microsoft.com/en-us/library/windows/desktop/ee418650.aspx)

**Comment by danthorpe** [comment]
Hi - just stumbled across this interesting little project and issue. Some great resources here!

Regarding subclassing `NSOperation` and implementing the KVO correctly, in Swift... I've done it similarly in [Operations](https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/Operation.swift#L356). In this project (which began life inspired by the WWDC sample code) we had an interesting bug which resulted from attempting to override `isReady`. There seems to be some strange KVO related bug in `NSOperation` regarding this, which resulted in ~ 1-2% of operations getting stuck despite `super.ready` being true. In the end to fix it, I had to remove any kind of alteration of the state machine. See https://github.com/danthorpe/Operations/issues/175 and https://github.com/danthorpe/Operations/pull/286. Now there are stress tests in this project which run 1000s of operations.

**Comment by flexaddicted** [comment]
@couchdeveloper Sorry for the delay. Thank you very much for detailed answer. Very useful blogs.
